image: hipay/gitlab-ci-base:jessie


#services:
#  - docker:dind
#variables:
#  DOCKER_HOST: tcp://docker:2375

#    - MASTER_HOST=$(docker inspect --format '{{ .NetworkSettings.Networks.hipayenterprisesdkprestashop_prestashop.IPAddress }}' hipay-enterprise-ps17-$CI_JOB_ID)
#    - docker exec mysql-ps17-$CI_JOB_ID mysql -e "update prestashop17.ps_shop_url set domain = '$MASTER_HOST', domain_ssl = '$MASTER_HOST' "


stages:
 - sync

sync:
  stage: sync
  script:
  - git clone --mirror https://$GITLAB_USER:$GITLAB_PASSWORD@gitlab.hipay.org/pi-ecommerce/hipay-enterprise-sdk-prestashop.git
  - cd hipay-enterprise-sdk-prestashop.git
  - git push --mirror https://$GITHUB_USER:$GITHUB_PASSWORD@github.com/hipay/hipay-enterprise-sdk-prestashop.git
  allow_failure: true